// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crud.appdatacontext;

#nullable disable

namespace crud.Migrations
{
    [DbContext(typeof(crudcontext))]
    [Migration("20240925150525_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("crud.entity.GHCT", b =>
                {
                    b.Property<Guid>("GhctId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MyProperty")
                        .HasColumnType("int");

                    b.Property<decimal>("giaDonVi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("gioHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("sanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("soLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("totalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GhctId");

                    b.HasIndex("gioHangId");

                    b.HasIndex("sanPhamId");

                    b.ToTable("gHCTs");
                });

            modelBuilder.Entity("crud.entity.GioHang", b =>
                {
                    b.Property<Guid>("gioHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("tongSoLuongSanPham")
                        .HasColumnType("int");

                    b.Property<decimal>("tongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("gioHangId");

                    b.ToTable("gioHangs");
                });

            modelBuilder.Entity("crud.entity.SanPham", b =>
                {
                    b.Property<Guid>("sanPhamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("soLuong")
                        .HasColumnType("int");

                    b.Property<string>("tenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sanPhamId");

                    b.ToTable("sanpham");
                });

            modelBuilder.Entity("crud.entity.GHCT", b =>
                {
                    b.HasOne("crud.entity.GioHang", "GioHang")
                        .WithMany("gHCTs")
                        .HasForeignKey("gioHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("crud.entity.SanPham", "SanPham")
                        .WithMany("gHCTs")
                        .HasForeignKey("sanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("crud.entity.GioHang", b =>
                {
                    b.Navigation("gHCTs");
                });

            modelBuilder.Entity("crud.entity.SanPham", b =>
                {
                    b.Navigation("gHCTs");
                });
#pragma warning restore 612, 618
        }
    }
}
